import { db } from "@/lib/db";
import { auditLog } from "@/lib/db/schema";

export const AUDIT_ACTIONS = {
  // ── Menu ──
  MENU_ITEM_CREATED: "MENU_ITEM_CREATED",
  MENU_ITEM_UPDATED: "MENU_ITEM_UPDATED",
  MENU_ITEM_DELETED: "MENU_ITEM_DELETED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  // ── Students ──
  STUDENT_CREATED: "STUDENT_CREATED",
  STUDENT_DELETED: "STUDENT_DELETED",
  STUDENT_PHOTO_UPDATED: "STUDENT_PHOTO_UPDATED",
  // ── Parents ──
  PARENT_CREATED: "PARENT_CREATED",
  PARENT_UPDATED: "PARENT_UPDATED",
  PARENT_DELETED: "PARENT_DELETED",
  // ── Accounts ──
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ACCOUNT_BULK_CREATED: "ACCOUNT_BULK_CREATED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  CREDENTIALS_SENT: "CREDENTIALS_SENT",
  // ── Cards / RFID ──
  CARD_ASSIGNED: "CARD_ASSIGNED",
  CARD_UNLINKED: "CARD_UNLINKED",
  TEMP_CARD_ISSUED: "TEMP_CARD_ISSUED",
  TEMP_CARD_REVOKED: "TEMP_CARD_REVOKED",
  GUEST_CARD_ISSUED: "GUEST_CARD_ISSUED",
  // ── Wallet / Finance ──
  UNITS_UPDATED: "UNITS_UPDATED",
  UNITS_RESET: "UNITS_RESET",
  WALLET_TOPUP: "WALLET_TOPUP",
  // ── Payments ──
  PAYMENT_EVENT_CREATED: "PAYMENT_EVENT_CREATED",
  PAYMENT_EVENT_UPDATED: "PAYMENT_EVENT_UPDATED",
  PAYMENT_EVENT_DELETED: "PAYMENT_EVENT_DELETED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_ACCOUNT_CREATED: "PAYMENT_ACCOUNT_CREATED",
  PAYMENT_ACCOUNT_REVIEWED: "PAYMENT_ACCOUNT_REVIEWED",
  PAYMENT_CONFIG_UPDATED: "PAYMENT_CONFIG_UPDATED",
  // ── Settlement ──
  SETTLEMENT_ACCOUNT_CREATED: "SETTLEMENT_ACCOUNT_CREATED",
  SETTLEMENT_ACCOUNT_APPROVED: "SETTLEMENT_ACCOUNT_APPROVED",
  SETTLEMENT_ACCOUNT_BLOCKED: "SETTLEMENT_ACCOUNT_BLOCKED",
  SETTLEMENT_ACCOUNT_UNBLOCKED: "SETTLEMENT_ACCOUNT_UNBLOCKED",
  CANTEEN_ROUTING_UPDATED: "CANTEEN_ROUTING_UPDATED",
  // ── Devices ──
  DEVICE_ACCOUNT_CREATED: "DEVICE_ACCOUNT_CREATED",
  DEVICE_STATUS_UPDATED: "DEVICE_STATUS_UPDATED",
  DEVICE_ASSIGNED: "DEVICE_ASSIGNED",
  DEVICE_UNASSIGNED: "DEVICE_UNASSIGNED",
  // ── Content / Notes / Assignments ──
  CONTENT_POST_CREATED: "CONTENT_POST_CREATED",
  CONTENT_POST_UPDATED: "CONTENT_POST_UPDATED",
  CONTENT_POST_DELETED: "CONTENT_POST_DELETED",
  CONTENT_SUBMITTED: "CONTENT_SUBMITTED",
  CONTENT_PERMISSION_GRANTED: "CONTENT_PERMISSION_GRANTED",
  CONTENT_PERMISSION_UPDATED: "CONTENT_PERMISSION_UPDATED",
  CONTENT_PERMISSION_REVOKED: "CONTENT_PERMISSION_REVOKED",
  CONTENT_TAG_CREATED: "CONTENT_TAG_CREATED",
  CONTENT_TAG_UPDATED: "CONTENT_TAG_UPDATED",
  CONTENT_TAG_DELETED: "CONTENT_TAG_DELETED",
  CONTENT_GROUP_CREATED: "CONTENT_GROUP_CREATED",
  CONTENT_GROUP_UPDATED: "CONTENT_GROUP_UPDATED",
  CONTENT_GROUP_DELETED: "CONTENT_GROUP_DELETED",
  // ── Bulk ──
  BULK_UPLOAD: "BULK_UPLOAD",
  // ── Library ──
  BOOK_CREATED: "BOOK_CREATED",
  BOOK_UPDATED: "BOOK_UPDATED",
  BOOK_ARCHIVED: "BOOK_ARCHIVED",
  BOOK_COPY_ADDED: "BOOK_COPY_ADDED",
  BOOK_COPY_UPDATED: "BOOK_COPY_UPDATED",
  BOOK_COPY_RETIRED: "BOOK_COPY_RETIRED",
  LIBRARY_SETTINGS_UPDATED: "LIBRARY_SETTINGS_UPDATED",
  LIBRARY_BULK_UPLOAD: "LIBRARY_BULK_UPLOAD",
  BOOK_ISSUED: "BOOK_ISSUED",
  BOOK_RETURNED: "BOOK_RETURNED",
  BOOK_REISSUED: "BOOK_REISSUED",
  BOOK_LOST_MARKED: "BOOK_LOST_MARKED",
  LIBRARY_FINE_DEDUCTED: "LIBRARY_FINE_DEDUCTED",
  RETURN_CONFIRMED: "RETURN_CONFIRMED",
  RETURN_REJECTED: "RETURN_REJECTED",
  READABLE_BOOK_CREATED: "READABLE_BOOK_CREATED",
  // ── Settings / Org ──
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  DISCOUNT_CREATED: "DISCOUNT_CREATED",
  DISCOUNT_UPDATED: "DISCOUNT_UPDATED",
  DISCOUNT_DELETED: "DISCOUNT_DELETED",
  NOTICE_CREATED: "NOTICE_CREATED",
  // ── Gate ──
  GATE_TAP: "GATE_TAP",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export async function logAudit({
  organizationId,
  userId,
  userRole,
  action,
  details,
  request,
}: {
  organizationId?: string | null;
  userId: string;
  userRole: string;
  action: AuditAction;
  details?: Record<string, unknown>;
  request?: Request;
}) {
  try {
    const ipAddress = request?.headers?.get("x-forwarded-for")?.split(",")[0]?.trim()
      || request?.headers?.get("x-real-ip")
      || null;
    const userAgent = request?.headers?.get("user-agent") || null;

    await db.insert(auditLog).values({
      organizationId: organizationId ?? null,
      userId,
      userRole,
      action,
      details: details ? JSON.stringify(details) : null,
      ipAddress,
      userAgent,
    });
  } catch (error) {
    // Non-critical — don't break the main operation
    console.error("Audit log error:", error);
  }
}
